import { useEffect, useState } from 'react'
import { useZoom } from './useZoom'
import type { BillboardData, BillboardDef } from '../loaders/billboards'
import { NumGrid, ToggleGrid } from './defFields'
import type { NumFieldDef } from './defFields'
import './BillboardViewer.css'

type Props = {
  data: BillboardData
  onSave: (data: BillboardData) => Promise<void>
  onDirtyChange?: (dirty: boolean) => void
}

const ZOOM_LEVELS = [1, 2, 4]

const GENERAL_FIELDS: NumFieldDef[] = [
  ['materialId', 'Material ID'],
  ['size2d', 'Width (size2d)'],
  ['size3d', 'Height (size3d)'],
]

// Value meanings from darkan-bot-refactor BillboardType.kt / BillboardEffect.kt.
const SHAPE_LABELS: Record<number, string> = {
  0: 'Rectangle',
  1: 'Circle',
  2: 'Brightened rectangle',
}

const BLEND_LABELS: Record<number, string> = {
  0: 'Colour mix',
  1: 'No colour mix',
}

// billboard type id -> model ids, generated by scripts/scan-billboard-usage.mjs.
// Fetched once and shared across every billboard page.
let usagePromise: Promise<Record<string, number[]>> | null = null
function loadUsage(): Promise<Record<string, number[]>> {
  usagePromise ??= fetch(`${import.meta.env.BASE_URL}billboard_usage.json`)
    .then((res) => (res.ok ? res.json() : {}))
    .catch(() => ({}))
  return usagePromise
}

export default function BillboardViewer({ data, onSave, onDirtyChange }: Props) {
  const [draft, setDraft] = useState<BillboardDef>(data.def)
  const [isDirty, setIsDirty] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [zoom, setZoom] = useZoom('cache-editor:billboard-zoom', ZOOM_LEVELS, 2)
  const [materialUrl, setMaterialUrl] = useState<string | null>(null)
  const [usedBy, setUsedBy] = useState<number[] | null>(null)

  useEffect(() => {
    let cancelled = false
    loadUsage().then((usage) => {
      if (!cancelled) setUsedBy(usage[String(data.id)] ?? [])
    })
    return () => { cancelled = true }
  }, [data.id])

  useEffect(() => {
    setDraft(data.def)
    setIsDirty(false)
  }, [data])

  useEffect(() => {
    onDirtyChange?.(isDirty)
  }, [isDirty, onDirtyChange])

  // Load the referenced material PNG (textures/<id>/<id>.png) for the preview.
  useEffect(() => {
    let cancelled = false
    let url: string | null = null
    setMaterialUrl(null)
    const materialId = draft.materialId ?? -1
    if (!data.texturesDir || materialId < 0) return
    async function load() {
      try {
        const subHandle = await data.texturesDir!.getDirectoryHandle(String(materialId))
        const fileHandle = await subHandle.getFileHandle(`${materialId}.png`)
        const file = await fileHandle.getFile()
        if (cancelled) return
        url = URL.createObjectURL(file)
        setMaterialUrl(url)
      } catch {
        // no material image for this id — preview stays empty
      }
    }
    load()
    return () => {
      cancelled = true
      if (url) URL.revokeObjectURL(url)
    }
  }, [draft.materialId, data.texturesDir])

  function set(key: string, value: unknown) {
    setDraft((prev) => ({ ...prev, [key]: value }))
    setIsDirty(true)
  }

  async function handleSave() {
    setIsSaving(true)
    await onSave({ ...data, def: draft })
    setIsSaving(false)
    setIsDirty(false)
  }

  const shape = draft.shape ?? 2

  return (
    <div className="item-viewer">
      <div className="item-header">
        <div className="item-badges">
          <span className="enum-title">Billboard {data.id}</span>
        </div>
      </div>

      <div className="hit-zoom-bar">
        <span className="hit-zoom-label">Zoom</span>
        <div className="hit-zoom-buttons">
          {ZOOM_LEVELS.map((z) => (
            <button
              key={z}
              type="button"
              className={`zoom-btn${zoom === z ? ' active' : ''}`}
              onClick={() => setZoom(z)}
            >
              {z}×
            </button>
          ))}
        </div>
      </div>

      <section className="item-section">
        <h3>Preview</h3>
        {materialUrl ? (
          <div className="hit-preview hit-preview-cell">
            <img
              src={materialUrl}
              alt=""
              className={`billboard-preview${shape === 1 ? ' billboard-circle' : ''}${shape === 2 ? ' billboard-brightened' : ''}`}
              style={{ width: (draft.size2d ?? 64) * zoom, height: (draft.size3d ?? 64) * zoom }}
            />
          </div>
        ) : (
          <p className="map-sprite-none">
            {data.texturesDir
              ? 'No material image resolves — set a valid material id to preview.'
              : 'No textures entry found in this cache — preview unavailable.'}
          </p>
        )}
      </section>

      <section className="item-section">
        <h3>Used By Models</h3>
        {usedBy == null ? (
          <p className="map-sprite-none">Loading usage index…</p>
        ) : usedBy.length === 0 ? (
          <p className="map-sprite-none">No models reference this billboard (per scripts/scan-billboard-usage.mjs — re-run it after model edits).</p>
        ) : (
          <p className="billboard-used-by">{usedBy.join(', ')}</p>
        )}
      </section>

      <section className="item-section">
        <h3>General</h3>
        <NumGrid fields={GENERAL_FIELDS} values={draft as unknown as Record<string, unknown>} onChange={(k, v) => set(k, v)} />
      </section>

      <section className="item-section">
        <h3>Rendering</h3>
        <div className="item-grid">
          <label className="item-field">
            <span className="item-field-label">Shape</span>
            <select
              className="item-stackable-select"
              value={shape}
              onChange={(e) => set('shape', parseInt(e.target.value, 10))}
            >
              {Object.entries(SHAPE_LABELS).map(([value, label]) => (
                <option key={value} value={value}>{label}</option>
              ))}
            </select>
          </label>
          <label className="item-field">
            <span className="item-field-label">Blend Type</span>
            <select
              className="item-stackable-select"
              value={draft.blendType ?? 1}
              onChange={(e) => set('blendType', parseInt(e.target.value, 10))}
            >
              {Object.entries(BLEND_LABELS).map(([value, label]) => (
                <option key={value} value={value}>{label}</option>
              ))}
            </select>
          </label>
        </div>
        <ToggleGrid
          fields={[['stationary', 'Stationary'], ['hasUid', 'Has UID']]}
          values={draft as unknown as Record<string, unknown>}
          onChange={(k, v) => set(k, v)}
        />
      </section>

      {isDirty && (
        <div className="save-bar">
          <span className="save-bar-label">Unsaved changes</span>
          <button type="button" className="save-bar-discard" onClick={() => { setDraft(data.def); setIsDirty(false) }}>Discard</button>
          <button type="button" className="save-bar-save" onClick={handleSave} disabled={isSaving}>
            {isSaving ? 'Saving…' : 'Save'}
          </button>
        </div>
      )}
    </div>
  )
}
